In [1]:
import pandas as pd
import numpy as np

In [2]:
user_hf = pd.read_csv('./data/user_handcrafted_features.csv')

In [3]:
user_svd = pd.read_csv('./data/users_svd_500.csv')

In [4]:
user_hf.head(10)

,new_use_id,old_use_id,taobao_record_count,taobao_buy_count,taobao_click_count,taobao_buy_ratio,taobao_items_buy_count,taobao_items_click_count,taobao_items_buy_ratio,taobao_cats_buy_count,taobao_cats_click_count,taobao_cats_buy_ratio,koubei_record_count,koubei_locations_count,koubei_merchant_count
0,0,1980536,1948,4,1944,0.002053,4,323,0.012232,2,25,0.074074,0,0,0
1,1,647747,337,8,329,0.023739,8,266,0.029197,5,27,0.156250,0,0,0
2,2,183647,431,79,352,0.183295,56,220,0.202899,18,27,0.400000,0,0,0
3,3,723956,384,59,325,0.153646,42,203,0.171429,17,23,0.425000,0,0,0
4,4,1781938,151,8,143,0.052980,8,99,0.074766,6,20,0.230769,0,0,0
5,5,1652831,370,15,355,0.040541,12,164,0.068182,7,16,0.304348,2,1,1
6,6,416403,1055,30,1025,0.028436,16,651,0.023988,9,30,0.230769,0,0,0
7,7,43130,249,31,218,0.124498,29,158,0.155080,9,24,0.272727,23,2,1
8,8,502518,316,26,290,0.082278,20,186,0.097087,7,22,0.241379,0,0,0
9,9,109400,221,9,212,0.040724,6,124,0.046154,5,11,0.312500,0,0,0

In [5]:
user_svd.head(10)

,svd_feature_1,svd_feature_2,svd_feature_3,svd_feature_4,svd_feature_5,svd_feature_6,svd_feature_7,svd_feature_8,svd_feature_9,svd_feature_10,...,svd_feature_493,svd_feature_494,svd_feature_495,svd_feature_496,svd_feature_497,svd_feature_498,svd_feature_499,svd_feature_500,new_id,old_id
0,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000004,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0,1980536
1,0.0,0.008640,0.000000,0.000000e+00,6.320582e-07,7.162586e-02,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.019406,1,647747
2,0.0,0.000000,0.000048,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000085,0.000000,0.000013,...,0.000000,0.0,0.003328,0.0,0.000000,0.001511,0.0,0.004518,2,183647
3,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.254896,3,723956
4,0.0,0.000033,0.000000,2.818866e-07,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000085,0.0,0.000233,0.0,0.002222,0.001763,0.0,0.000795,4,1781938
5,0.0,0.000000,0.000008,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000094,0.000025,...,0.000000,0.0,0.000000,0.0,0.021140,0.000000,0.0,0.000000,5,1652831
6,0.0,0.008648,0.000000,0.000000e+00,5.347948e-04,0.000000e+00,0.010244,0.000000,0.000000,0.000062,...,0.000000,0.0,0.000000,0.0,0.009753,0.000000,0.0,0.000000,6,416403
7,0.0,0.000034,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000045,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000104,7,43130
8,0.0,0.155552,0.000000,0.000000e+00,0.000000e+00,1.226982e-05,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,8,502518
9,0.0,0.008637,0.000011,0.000000e+00,0.000000e+00,7.399375e-07,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.0,0.003665,0.000000,0.0,0.000000,9,109400

In [7]:
user_svd_100 = user_svd.iloc[:, :100]

In [12]:
users = pd.concat([user_hf, user_svd_100], axis = 1)

In [13]:
users.head(10)

,new_use_id,old_use_id,taobao_record_count,taobao_buy_count,taobao_click_count,taobao_buy_ratio,taobao_items_buy_count,taobao_items_click_count,taobao_items_buy_ratio,taobao_cats_buy_count,...,svd_feature_91,svd_feature_92,svd_feature_93,svd_feature_94,svd_feature_95,svd_feature_96,svd_feature_97,svd_feature_98,svd_feature_99,svd_feature_100
0,0,1980536,1948,4,1944,0.002053,4,323,0.012232,2,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.113512,0.000000,0.000000
1,1,647747,337,8,329,0.023739,8,266,0.029197,5,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000610,0.0,0.060873,0.000196,0.000000
2,2,183647,431,79,352,0.183295,56,220,0.202899,18,...,0.000000,0.000000,0.000081,0.000000,0.000713,0.000251,0.0,0.000013,0.000020,0.000000
3,3,723956,384,59,325,0.153646,42,203,0.171429,17,...,0.000000,0.000000,0.000204,0.000000,0.000000,0.000000,0.0,0.000000,0.030745,0.000000
4,4,1781938,151,8,143,0.052980,8,99,0.074766,6,...,0.000000,0.000000,0.000000,0.000000,0.000297,0.000081,0.0,0.000191,0.000003,0.000481
5,5,1652831,370,15,355,0.040541,12,164,0.068182,7,...,0.000000,0.000000,0.000000,0.000000,0.000171,0.000000,0.0,0.000000,0.000000,0.000000
6,6,416403,1055,30,1025,0.028436,16,651,0.023988,9,...,0.000524,0.000281,0.000000,0.000000,0.000112,0.000000,0.0,0.000901,0.000000,0.000000
7,7,43130,249,31,218,0.124498,29,158,0.155080,9,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000141
8,8,502518,316,26,290,0.082278,20,186,0.097087,7,...,0.000000,0.000000,0.000575,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000226
9,9,109400,221,9,212,0.040724,6,124,0.046154,5,...,0.000000,0.000000,0.000002,0.000023,0.000000,0.000000,0.0,0.000000,0.000000,0.000000

In [14]:
users.shape

(963923, 115)

In [16]:
users.to_csv('./data/users_115.csv', index = False)